POST http://localhost:1111/signup
Content-Type: application/json

{
    "username":"Prakash",
    "password":"2020",
    "fullname":"Prakash",
    "contact":11222121,
     "wishlist":[ ]
}

###

###
POST  http://localhost:1111/signin
Content-Type: application/json

{
    "username":"dpz",
    "password":"3333"
}
###POST RECIPE

POST http://localhost:1111/postrecipe
Content-Type: application/json

    {
        "recipeName": "Chocolate Cake",
        "cuisine": "American",
        "ingredient": "Chocolate, Flour, Sugar, Eggs, Butter, Baking Powder",
        "duration": "60 minutes",
        "type": "Dessert"
    }
###
### GET ALL RECIPE
GET http://localhost:1111/

###

### GET RECIPE BY ID 
GET http://localhost:1111/6699186c161cb8bff7f39834

###



### PUT /add-to-wishlist

PUT http://localhost:1111/update/dpz/6
###

### PUT /wishlist remove

PUT http://localhost:1111/remove/dpz/6
###

### GET wishlist by username
GET http://localhost:1111/getwishlist/dpz

###


### GET wishlist by username
GET http://localhost:1111/recipename/Chicken 65

###


###